### PR TITLE
Sm 12 post demos

### PR DESCRIPTION
**Pull request by RLodge1**
Created a file with mongo interaction functions. Some may need to be added, but functionality for creating/editing/deleting users is well tested. Some functionality for companies has been added, but more functions will likely be needed later.

This should provide a basis for request handler functions to deal with mongo for next phase of backend development

P.S. I requested everyone to review, but as long as somebody approves we can merge. Doesn't need to be everyone.

### CODE REVIEW

**Review by iyad-obeid — APPROVED** [review]
This looks great and I would go ahead and merge. However be advised that it's complaining about the package-lock.json and package.json files. I think you can just exclude those from the merge somehow? They don't really matter, at least not for what you're trying to do in this merge. Otherwise, I approve!

**Comment by leo6liu** [comment]
I resolved the package and package-lock issues that Dr. Obeid mentioned.

**Review by leo6liu — CHANGES_REQUESTED** [review]
Looks like you are connecting a mongo client twice. I think you can remove the changes to app.js, it only needs to live in the mongo utility file.

**Comment by RLodge1** [comment]
Leo, I agree with throwing out the app.js changes here. Is there a way to discard those changes and keep the new file?

**Comment by RLodge1** [comment]
Nevermind, I fixed it

**Pull request merged**
